#!/usr/bin/env python3
"""Check the licence texts in licenses/ against their upstream sources.

Every file under licenses/ (except MANIFEST.csv and EMBEDDED-COPYRIGHTS.txt)
is a byte-for-byte copy of an upstream licence file. MANIFEST.csv gives, for
each one, its SHA-256 and the pinned URL it was downloaded from.
EMBEDDED-COPYRIGHTS.txt lists each embedded font's own copyright record
(OpenType `name` ID 0), decoded from LeanSvg/Fonts/*.lean.

    python3 tests/check_licenses.py           # offline: hashes, file set, copyrights
    python3 tests/check_licenses.py --online  # also re-download every URL and compare
    python3 tests/check_licenses.py --write-copyrights  # regenerate EMBEDDED-COPYRIGHTS.txt

A URL ending in `#member` names a file inside a .tar.xz archive.
"""
import base64
import csv
import hashlib
import io
import re
import struct
import sys
import tarfile
import urllib.request
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
LIC = REPO / "licenses"
COPYRIGHTS = LIC / "fonts" / "EMBEDDED-COPYRIGHTS.txt"


def sha(b: bytes) -> str:
    return hashlib.sha256(b).hexdigest()


def manifest() -> list[dict]:
    rows = list(csv.DictReader(open(LIC / "MANIFEST.csv", newline="")))
    assert rows and list(rows[0]) == ["file", "sha256", "source_url", "covers"]
    files = [r["file"] for r in rows]
    assert len(files) == len(set(files)), "duplicate manifest entry"
    for r in rows:
        assert re.fullmatch(r"[0-9a-f]{64}", r["sha256"]), r
        assert r["source_url"].startswith("https://"), r
        assert r["covers"].strip(), r
    return rows


def font_copyright(lean: Path) -> str:
    """`name` ID 0 of the font embedded in one LeanSvg/Fonts module."""
    m = re.search(r"def front : Array String := #\[(.*?)\]", lean.read_text(), re.S)
    assert m, lean
    b = base64.b64decode("".join(re.findall(r'"([^"]*)"', m.group(1))))
    n = struct.unpack(">H", b[4:6])[0]
    tabs = {b[12 + 16 * i:16 + 16 * i]: struct.unpack(">II", b[20 + 16 * i:28 + 16 * i]) for i in range(n)}
    off, ln = tabs[b"name"]
    assert off + ln <= len(b), lean
    t = b[off:off + ln]
    cnt, so = struct.unpack(">HH", t[2:6])
    found = {}
    for i in range(cnt):
        pid, eid, lid, nid, l, o = struct.unpack(">HHHHHH", t[6 + 12 * i:18 + 12 * i])
        if nid == 0:
            s = t[so + o:so + o + l]
            found[(pid, lid)] = s.decode("utf-16-be") if pid in (0, 3) else s.decode("latin1")
    for key in ((3, 0x409), (1, 0), (0, 0), (0, 3)):
        if key in found:
            return found[key].strip()
    raise AssertionError(f"{lean}: no copyright record")


def copyrights_text() -> str:
    mods = sorted((REPO / "LeanSvg" / "Fonts").glob("*.lean"))
    assert mods
    out = ["Copyright records of the fonts embedded in lean-svg, copied verbatim",
           "from each font's OpenType `name` table (ID 0). Generated by",
           "tests/check_licenses.py --write-copyrights; do not edit by hand.", ""]
    for m in mods:
        out += [f"{m.stem}:"] + ["    " + l for l in font_copyright(m).splitlines()] + [""]
    return "\n".join(out)


def fetch(url: str) -> bytes:
    base, _, member = url.partition("#")
    with urllib.request.urlopen(base, timeout=120) as r:
        data = r.read()
    if not member:
        return data
    with tarfile.open(fileobj=io.BytesIO(data), mode="r:xz") as tar:
        f = tar.extractfile(member)
        assert f, f"{member} not in {base}"
        return f.read()


def main() -> None:
    if "--write-copyrights" in sys.argv:
        COPYRIGHTS.write_text(copyrights_text())
        print(f"wrote {COPYRIGHTS.relative_to(REPO)}")
        return
    rows = manifest()
    on_disk = {str(p.relative_to(LIC)) for p in LIC.rglob("*") if p.is_file()}
    on_disk -= {"MANIFEST.csv", str(COPYRIGHTS.relative_to(LIC))}
    assert on_disk == {r["file"] for r in rows}, (
        f"not in manifest: {sorted(on_disk - {r['file'] for r in rows})}; "
        f"missing: {sorted({r['file'] for r in rows} - on_disk)}")
    for r in rows:
        got = sha((LIC / r["file"]).read_bytes())
        assert got == r["sha256"], f"{r['file']}: sha256 {got} != manifest {r['sha256']}"
    assert COPYRIGHTS.read_text() == copyrights_text(), (
        f"{COPYRIGHTS.relative_to(REPO)} is stale: run --write-copyrights")
    print(f"{len(rows)} licence files match MANIFEST.csv; embedded copyrights current")
    if "--online" in sys.argv:
        for r in rows:
            got = sha(fetch(r["source_url"]))
            assert got == r["sha256"], f"{r['file']}: upstream sha256 {got} != {r['sha256']} ({r['source_url']})"
            print(f"identical to upstream: {r['file']}")
        print(f"{len(rows)} licence files byte-identical to their upstream URLs")


if __name__ == "__main__":
    main()
