#!/usr/bin/env python3
"""Generate the packed data section of LeanSvg/Bidi.lean.

Sources (read from the local cargo registry, no network):
  * unicode-bidi-0.3.18/src/char_data/tables.rs  -> bidi_class_table, bidi_pairs_table
  * harfrust-0.12.0/src/hb/ucd_table.rs          -> _hb_ucd_bmg (Bidi_Mirroring_Glyph)

Usage:  python3 gen_bidi_tables.py [LeanSvg/Bidi.lean]
Rewrites the region between the `-- BEGIN GENERATED` / `-- END GENERATED`
markers of the given Lean file in place (or prints it when no file is given).
"""
import glob
import os
import re
import sys

REG = os.path.expanduser("~/.cargo/registry/src/*/")
BIDI_TABLES = glob.glob(REG + "unicode-bidi-0.3.18/src/char_data/tables.rs")[0]
HB_UCD = glob.glob(REG + "harfrust-0.12.0/src/hb/ucd_table.rs")[0]

# Must match the constructor order of `LeanSvg.Bidi.Cls`.
CLASSES = ["L", "R", "AL", "EN", "ES", "ET", "AN", "CS", "NSM", "BN", "B", "S", "WS",
           "ON", "LRE", "LRO", "RLE", "RLO", "PDF", "LRI", "RLI", "FSI", "PDI"]


def class_ranges():
    src = open(BIDI_TABLES).read()
    body = src[src.index("bidi_class_table"):src.index("bidi_pairs_table")]
    rng = [(int(a, 16), int(b, 16), c) for a, b, c in
           re.findall(r"\('\\u\{([0-9a-f]+)\}',\s*'\\u\{([0-9a-f]+)\}',\s*(\w+)\)", body)]
    assert len(rng) == body.count("('\\u{"), "table parse incomplete"
    # Fill gaps with the crate's fallback `L`, merge equal neighbours, keep starts only.
    out = []
    nxt = 0
    for a, b, c in rng:
        assert a >= nxt
        if a > nxt:
            out.append((nxt, "L"))
        out.append((a, c))
        nxt = b + 1
    if nxt <= 0x10FFFF:
        out.append((nxt, "L"))
    merged = []
    for a, c in out:
        if merged and merged[-1][1] == c:
            continue
        merged.append((a, c))
    return merged


def bracket_pairs():
    src = open(BIDI_TABLES).read()
    body = src[src.index("bidi_pairs_table"):]
    res = []
    for a, b, s in re.findall(
            r"\('\\u\{([0-9a-f]+)\}',\s*'\\u\{([0-9a-f]+)\}',\s*(None|Some\('\\u\{[0-9a-f]+\}'\))\)", body):
        o, c = int(a, 16), int(b, 16)
        sk = o if s == "None" else int(re.search(r"\{([0-9a-f]+)\}", s).group(1), 16)
        res.append((o, c, sk))
    assert len(res) == len(re.findall(r"(?<!Some)\('\\u\{", body)), "pairs parse incomplete"
    return res


def hb_array(src, name):
    m = re.search(r"static " + name + r": \[\w+; \d+\]\s*=\s*\[(.*?)\];", src, re.S)
    return [int(x) for x in m.group(1).replace("\n", " ").split(",") if x.strip()]


def mirror_pairs():
    src = open(HB_UCD).read()
    u8 = hb_array(src, "_hb_ucd_u8")
    i16 = hb_array(src, "_hb_ucd_i16")
    fn = src[src.index("fn _hb_ucd_bmg"):]
    fn = fn[:fn.index("\n}")]
    # Check the packtab layout we transcribe below is still the one in the file.
    assert "u<65380usize" in fn and "10874usize" in fn and "11002usize" in fn and "11118usize" in fn

    def b4(base, i):
        return (u8[base + (i >> 1)] >> ((i & 1) << 2)) & 15

    def bmg(u):
        if u >= 65380:
            return 0
        x = b4(10874, u >> 8)
        y = u8[11002 + (x << 3) + ((u >> 5) & 7)]
        z = u8[11118 + (y << 3) + ((u >> 2) & 7)]
        return i16[z + (u & 3)]

    res = [(u, u + bmg(u)) for u in range(65380) if bmg(u) != 0]
    assert (0x28, 0x29) in res and (0x29, 0x28) in res and (0x3C, 0x3E) in res
    return res


def wrap(s, width=96):
    return "\n".join('  "' + s[i:i + width] + '" ++' for i in range(0, len(s), width))[:-3]


def emit():
    cr = class_ranges()
    br = bracket_pairs()
    mr = mirror_pairs()
    cls_hex = "".join("%06x%02x" % (a, CLASSES.index(c)) for a, c in cr)
    br_hex = "".join("%06x%06x%06x" % t for t in br)
    mr_hex = "".join("%06x%06x" % t for t in mr)
    return f"""-- BEGIN GENERATED by `python3 gen_bidi_tables.py LeanSvg/Bidi.lean` -- do not edit.

/-- `Bidi_Class` ranges of unicode-bidi 0.3.18 (Unicode 16.0.0), gaps filled with
the crate's fallback `L`: {len(cr)} records of `start:u24 class:u8`, hex. -/
def classHex : String :=
{wrap(cls_hex)}

/-- unicode-bidi 0.3.18 `bidi_pairs_table`, in table order: {len(br)} records of
`open:u24 close:u24 skeleton:u24` (skeleton = canonical opening bracket), hex. -/
def bracketHex : String :=
{wrap(br_hex)}

/-- harfrust 0.12.0 `_hb_ucd_bmg` expanded: {len(mr)} records of `cp:u24 mirror:u24`,
sorted by `cp`, hex. -/
def mirrorHex : String :=
{wrap(mr_hex)}

-- END GENERATED
"""


if __name__ == "__main__":
    text = emit()
    if len(sys.argv) > 1:
        path = sys.argv[1]
        cur = open(path).read()
        a = cur.index("-- BEGIN GENERATED")
        b = cur.index("-- END GENERATED\n") + len("-- END GENERATED\n")
        open(path, "w").write(cur[:a] + text + cur[b:])
    else:
        sys.stdout.write(text)
