#!/usr/bin/env python3
"""Generate a Lean module embedding a subsetted TrueType font (T25).

Runs `pyftsubset` on an input `.ttf`, then hex-encodes the subsetted bytes
into `MicroSvg/Fonts/<Module>.lean`: an `Array String` of short hex chunks
(rather than one giant string literal — measured to keep `lake build` fast,
see the T25 Report) plus `def bytes : ByteArray := Font.hexDecodeChunks chunks`.

    python3 tests/gen_font_module.py <input.ttf> <ModuleName> [options]

Options:
    --unicodes RANGES     passed straight to pyftsubset (default: Basic Latin,
                           Latin-1 Supplement, Latin Extended-A, General
                           Punctuation)
    --chunk-hex-chars N   hex characters (2 per byte) per chunk string
                           (default 20000, i.e. 10 KB of font data per chunk)
    --pyftsubset PATH     path to the pyftsubset executable (default: look on
                           PATH, then next to this interpreter's user base)
    --out PATH            output .lean path (default MicroSvg/Fonts/<Module>.lean)
    --keep-subset PATH    also save the intermediate subsetted .ttf here

Prints the exact pyftsubset command and the before/after sizes, for the
task's Report.
"""

from __future__ import annotations

import argparse
import shutil
import site
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# Basic Latin, Latin-1 Supplement, Latin Extended-A, General Punctuation, plus
# U+20AC (Euro sign, Currency Symbols block) so that check_font.py's default
# probe string -- which the T25 spec itself defines to include "€" -- lands on
# a real glyph rather than trivially matching .notdef on both sides.
DEFAULT_UNICODES = "U+0020-007F,U+00A0-00FF,U+0100-017F,U+2000-206F,U+20AC"
DEFAULT_CHUNK_HEX_CHARS = 20000


def find_pyftsubset(explicit: str | None) -> str:
    if explicit:
        return explicit
    found = shutil.which("pyftsubset")
    if found:
        return found
    candidate = Path(site.getuserbase()) / "bin" / "pyftsubset"
    if candidate.exists():
        return str(candidate)
    sys.exit(
        "pyftsubset not found on PATH or in the user site bin directory; "
        "install with: pip3 install --user fonttools"
    )


def subset_font(pyftsubset: str, src: Path, dst: Path, unicodes: str) -> list[str]:
    cmd = [
        pyftsubset,
        str(src),
        f"--output-file={dst}",
        f"--unicodes={unicodes}",
        "--no-hinting",
        "--layout-features=kern",
        "--glyph-names",
        "--notdef-outline",
    ]
    subprocess.run(cmd, check=True)
    return cmd


def to_lean_module(data: bytes, module: str, chunk_hex_chars: int) -> str:
    hexstr = data.hex()
    chunks = [hexstr[i : i + chunk_hex_chars] for i in range(0, len(hexstr), chunk_hex_chars)]
    lines = [
        "-- Generated by tests/gen_font_module.py. Do not edit by hand.",
        f"-- {len(data)} bytes of embedded, subsetted TrueType font data.",
        "import MicroSvg.Font",
        "",
        f"namespace MicroSvg.Fonts.{module}",
        "",
        "/-- Hex-encoded subsetted font bytes, split into short chunks so `lake",
        "build` never has to parse one giant string literal (see the T25 Report",
        "in tasks/T25-font-parser.md for the measured effect). -/",
        "def chunks : Array String := #[",
    ]
    lines += [f'  "{c}",' for c in chunks]
    lines += [
        "]",
        "",
        "/-- The subsetted font, ready for `MicroSvg.Font.parse`. -/",
        "def bytes : ByteArray := MicroSvg.Font.hexDecodeChunks chunks",
        "",
        f"end MicroSvg.Fonts.{module}",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("ttf", type=Path)
    ap.add_argument("module", help="Lean module name, e.g. NotoSans")
    ap.add_argument("--unicodes", default=DEFAULT_UNICODES)
    ap.add_argument("--chunk-hex-chars", type=int, default=DEFAULT_CHUNK_HEX_CHARS)
    ap.add_argument("--pyftsubset", default=None)
    ap.add_argument("--out", type=Path, default=None)
    ap.add_argument("--keep-subset", type=Path, default=None)
    args = ap.parse_args()

    pyftsubset = find_pyftsubset(args.pyftsubset)
    subset_path = args.keep_subset or Path(f"/tmp/{args.module}.subset.ttf")
    cmd = subset_font(pyftsubset, args.ttf, subset_path, args.unicodes)
    data = subset_path.read_bytes()

    out = args.out or (REPO / "MicroSvg" / "Fonts" / f"{args.module}.lean")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(to_lean_module(data, args.module, args.chunk_hex_chars))

    print("command:", " ".join(cmd))
    print(
        f"{args.ttf.name}: {args.ttf.stat().st_size} bytes -> "
        f"subset {len(data)} bytes -> {out.relative_to(REPO)} "
        f"({out.stat().st_size} bytes of Lean source, {len(data.hex()) // args.chunk_hex_chars + 1} chunks)"
    )


if __name__ == "__main__":
    main()
