#!/usr/bin/env python3
"""Generate LeanSvg/StixNonUnicode.lean: matplotlib's private-use code points
for the STIX 1.x "STIXNonUnicode" font, mapped back to real Unicode.

matplotlib's mathtext ("stix"/"stixsans" font sets) writes calligraphic,
italic/bold blackboard and sans-serif Greek letters as Private Use Area code
points in font-family "STIXNonUnicode" (matplotlib's `stix_virtual_fonts`,
lib/matplotlib/_mathtext_data.py). That font is not installed anywhere, so
the letters draw as boxes (lean-svg) or nothing (Chromium). This table maps
each such code point to the Unicode Mathematical Alphanumeric letter it
stands for (calligraphic -> script, blackboard -> double-struck, which has
no italic/bold forms in Unicode) or, for sans-serif Greek, the plain Greek
letter.

    python3 tests/gen_stix_nonunicode.py path/to/_mathtext_data.py

Source: matplotlib v3.9.2 `_mathtext_data.py` (Matplotlib License,
BSD-compatible; see NOTICE).
"""
import importlib.util
import sys
from pathlib import Path

# Letters that Unicode encodes outside the Mathematical Alphanumeric block.
SCRIPT_CAPS = {"B": 0x212C, "E": 0x2130, "F": 0x2131, "H": 0x210B,
               "I": 0x2110, "L": 0x2112, "M": 0x2133, "R": 0x211B}
DOUBLE_CAPS = {"C": 0x2102, "H": 0x210D, "N": 0x2115, "P": 0x2119,
               "Q": 0x211A, "R": 0x211D, "Z": 0x2124}


def target(font: str, ch: int) -> int:
    c = chr(ch)
    if font == "cal":
        assert "A" <= c <= "Z", c
        return SCRIPT_CAPS.get(c, 0x1D49C + ord(c) - ord("A"))
    if font == "bb":
        if "A" <= c <= "Z":
            return DOUBLE_CAPS.get(c, 0x1D538 + ord(c) - ord("A"))
        assert "a" <= c <= "z", c
        return 0x1D552 + ord(c) - ord("a")
    if font == "sf":
        assert 0x391 <= ch <= 0x3F5 or ch == 0x2202, hex(ch)
        return ch
    raise AssertionError(font)


def main() -> None:
    src = Path(sys.argv[1])
    spec = importlib.util.spec_from_file_location("mtd", src)
    mtd = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mtd)
    pairs: dict[int, int] = {}
    for font, styles in mtd.stix_virtual_fonts.items():
        items = styles.items() if isinstance(styles, dict) else [("", styles)]
        for _style, ranges in items:
            for lo, hi, _sub, pua in ranges:
                if not 0xE000 <= pua <= 0xF8FF:
                    continue
                for k in range(hi - lo + 1):
                    ch = lo + k
                    if font == "sf" and ch == 0x3A2:
                        continue  # no capital final sigma
                    code = pua + k
                    t = target(font, ch)
                    assert pairs.get(code, t) == t, (hex(code), hex(t))
                    pairs[code] = t
    rows = sorted(pairs.items())
    assert rows and all(0xE000 <= a <= 0xF8FF for a, _ in rows)
    out = [
        "-- Generated by tests/gen_stix_nonunicode.py. Do not edit by hand.",
        "-- matplotlib's STIXNonUnicode private-use code points -> Unicode",
        "-- (matplotlib v3.9.2 `stix_virtual_fonts`, Matplotlib License).",
        "",
        "namespace LeanSvg.StixNonUnicode",
        "",
        "/-- Sorted `(private-use code point, Unicode code point)` pairs. -/",
        "def table : Array (Nat × Nat) := #[",
    ]
    out += [f"  (0x{a:X}, 0x{b:X}){',' if i + 1 < len(rows) else ''}"
            for i, (a, b) in enumerate(rows)]
    out += ["]", "", "end LeanSvg.StixNonUnicode", ""]
    Path("LeanSvg/StixNonUnicodeTable.lean").write_text("\n".join(out))
    print(f"{len(rows)} code points")


if __name__ == "__main__":
    main()
