#!/usr/bin/env python3
"""Generate LeanSvg/BrotliData.lean (T105): RFC 7932's static dictionary,
its 121 word transforms and the literal context lookup table.

Inputs are dumped from the brotli 1.2.0 C sources (MIT, `pip download
--no-binary :all: brotli`) by a small C program that calls
`BrotliGetDictionary()`, `BrotliGetTransforms()` and reads
`_kBrotliContextLookupTable`:

    dict.bin        122784 bytes, sha256 20e42eb1...35c70 (RFC 7932 App. A)
    transforms.txt  one line per transform: "<type> <prefix hex>- <suffix hex>-"
    ctx.bin         2048 bytes

    python3 tests/gen_brotli_data.py dict.bin transforms.txt ctx.bin > LeanSvg/BrotliData.lean
"""
import base64
import hashlib
import sys

DICT_SHA = "20e42eb1b511c21806d4d227d07e5dd06877d8ce7b3a817f378f313653f35c70"


def lean_bytes(bs):
    return "#[" + ", ".join(str(b) for b in bs) + "]"


def main():
    d = open(sys.argv[1], "rb").read()
    assert len(d) == 122784 and hashlib.sha256(d).hexdigest() == DICT_SHA
    ts = []
    for line in open(sys.argv[2]):
        t, p, s = line.split()
        ts.append((int(t), bytes.fromhex(p[:-1]), bytes.fromhex(s[:-1])))
    assert len(ts) == 121
    ctx = open(sys.argv[3], "rb").read()
    assert len(ctx) == 2048
    b64 = base64.b64encode(d).decode()
    per = 4096
    chunks = [b64[i:i + per] for i in range(0, len(b64), per)]
    print("-- Generated by tests/gen_brotli_data.py. Do not edit by hand.")
    print("-- Brotli (RFC 7932) static data, from the brotli 1.2.0 sources (MIT licence).")
    print("import LeanSvg.Font")
    print()
    print("namespace LeanSvg.BrotliData")
    print()
    print("/-- RFC 7932 Appendix A, the static dictionary (122784 bytes), base64. -/")
    print("def dictChunks : Array String := #[")
    print(",\n".join('  "%s"' % c for c in chunks))
    print("]")
    print()
    print("/-- The 121 word transforms of RFC 7932 Appendix B: prefix, type (0 identity,")
    print("1-9 omit last n, 10 uppercase first, 11 uppercase all, 12-20 omit first 1-9),")
    print("suffix, as bytes. -/")
    print("def transforms : Array (Array UInt8 × Nat × Array UInt8) := #[")
    rows = []
    for t, p, s in ts:
        rows.append("  (%s, %d, %s)" % (lean_bytes(p), t, lean_bytes(s)))
    print(",\n".join(rows))
    print("]")
    print()
    print("/-- The literal context lookup (RFC 7932 section 7.1) for the four modes,")
    print("512 bytes each: context = lut[p1] ||| lut[256 + p2]; base64. -/")
    print('def contextLut : String := "%s"' % base64.b64encode(ctx).decode())
    print()
    print("end LeanSvg.BrotliData")


main()
