/-!
# Unicode Bidirectional Algorithm (UAX #9): a pure, total port of unicode-bidi 0.3.18

usvg lays out mixed-direction text with the Rust crate `unicode-bidi` 0.3.18
(`BidiInfo::new(text, Some(level))`, then `visual_runs(para, para.range)`),
and shapes each run with harfrust, which mirrors brackets etc. in RTL runs.
This module reproduces those results exactly, codepoint by codepoint:

* `bidiClass`  — the crate's `Bidi_Class` table (Unicode 16.0.0; unlisted
  codepoints are `L`, as in the crate).
* `paragraphLevels` — the crate's `BidiInfo.levels`: P3 is replaced by the
  caller's explicit paragraph level, then X1–X8 (directional status stack of
  depth 125, with the "Retaining Explicit Formatting Characters" variant the
  crate implements: X9-removed characters keep a level and class `BN`), X10
  (isolating run sequences with the crate's `sos`/`eos` choices), W1–W7,
  N0 (BD16 bracket pairs, 63-entry stack, canonical-equivalent brackets
  U+2329/U+232A ≡ U+3008/U+3009), N1–N2, I1–I2, and finally the crate's
  `assign_levels_to_removed_chars` (each X9-removed character takes the
  level of the character before it).
* `levels`     — `reordered_levels` for one line spanning the whole text:
  L1 (trailing whitespace and isolate controls, and segment/paragraph
  separators with the whitespace before them, reset to the paragraph level;
  X9-removed characters take the level of the character before them).
* `visualRuns` — L2 as `visual_runs` returns it: maximal same-level runs in
  visual order. L3 (combining marks) and L4 (mirroring) are not applied here,
  as in the crate; `mirror` provides harfrust's `Bidi_Mirroring_Glyph` for
  the caller's L4.

The crate works on UTF-8 byte offsets; everything here is per codepoint. The
crate's byte-level loops give every byte of a character the same class and
level, so the per-codepoint formulation computes the same result. The crate's
departures from the letter of UAX #9 are reproduced on purpose, e.g.:
`iter_backwards_from` walks earlier level runs of a sequence *forwards*
(`backScan`, used by N0's preceding-strong search and the BN clean-ups);
X5c only looks at the innermost open isolate; a BD16 stack overflow only
abandons the rest of the current level run; the last level run's `eos` is the
paragraph direction when the last non-removed character *before its end in the
text* is an isolate initiator; the N0 embedding direction is the level of the
sequence's first character even when X9 removes it.

**Paragraphs.** The whole input is treated as ONE paragraph, even if it
contains a paragraph separator (class `B`, e.g. U+2029 or `\n`): a `B` inside
the text behaves as in the crate's single-paragraph `ParagraphBidiInfo`
(level = paragraph level, neutral in N1, reset by L1), and the FSI
look-ahead / isolate matching do not stop at it. `BidiInfo::new` would split
the text there instead; usvg only reads `paragraphs[0]`, and its text chunks
never contain `B`, so the two agree on every input usvg produces.

Every loop is a `for` over a range bounded by the input size or a constant;
the only super-linear parts are the W4 look-ahead and N0 bracket scans, which
are bounded by the square of the input length (as in the crate).
-/

namespace LeanSvg.Bidi

/-! ## Bidi classes -/

/-- `Bidi_Class` values (UAX #9 table 4). The constructor order is the one the
generated table below uses. -/
inductive Cls where
  | L | R | AL | EN | ES | ET | AN | CS | NSM | BN | B | S | WS | ON
  | LRE | LRO | RLE | RLO | PDF | LRI | RLI | FSI | PDI
  deriving DecidableEq, Repr, Inhabited, BEq

/-- The class with table index `k` (constructor order), `L` if out of range. -/
def clsOfIndex (k : Nat) : Cls :=
  #[Cls.L, .R, .AL, .EN, .ES, .ET, .AN, .CS, .NSM, .BN, .B, .S, .WS, .ON,
    .LRE, .LRO, .RLE, .RLO, .PDF, .LRI, .RLI, .FSI, .PDI].getD k .L

/-- Removed by rule X9 (the crate's `removed_by_x9`). -/
def removedX9 : Cls → Bool
  | .RLE | .LRE | .RLO | .LRO | .PDF | .BN => true
  | _ => false

/-- Isolate initiator (`RLI`, `LRI`, `FSI`). -/
def isIsoInit : Cls → Bool
  | .RLI | .LRI | .FSI => true
  | _ => false

/-- Neutral or isolate formatting character (`NI` in UAX #9). -/
def isNI : Cls → Bool
  | .B | .S | .WS | .ON | .FSI | .LRI | .RLI | .PDI => true
  | _ => false

/-- The embedding direction of a level: `L` for even, `R` for odd. -/
def levelCls (l : Nat) : Cls := if l % 2 == 0 then .L else .R

/-! ## Generated data -/

-- BEGIN GENERATED by `python3 gen_bidi_tables.py LeanSvg/Bidi.lean` -- do not edit.

/-- `Bidi_Class` ranges of unicode-bidi 0.3.18 (Unicode 16.0.0), gaps filled with
the crate's fallback `L`: 1215 records of `start:u24 class:u8`, hex. -/
def classHex : String :=
  "000000090000090b00000a0a00000b0b00000c0c00000d0a00000e0900001c0a00001f0b0000200c0000210d00002305" ++
  "0000260d00002b0400002c0700002d0400002e070000300300003a0700003b0d0000410000005b0d0000610000007b0d" ++
  "00007f090000850a000086090000a0070000a10d0000a2050000a60d0000aa000000ab0d0000ad090000ae0d0000b005" ++
  "0000b2030000b40d0000b5000000b60d0000b9030000ba000000bb0d0000c0000000d70d0000d8000000f70d0000f800" ++
  "0002b90d0002bb000002c20d0002d0000002d20d0002e0000002e50d0002ee000002ef0d00030008000370000003740d" ++
  "0003760000037e0d00037f000003840d000386000003870d000388000003f60d0003f7000004830800048a0000058a0d" ++
  "00058b0000058d0d00058f0500059001000591080005be010005bf080005c0010005c1080005c3010005c4080005c601" ++
  "0005c7080005c801000600060006060d000608020006090500060b0200060c0700060d0200060e0d0006100800061b02" ++
  "00064b080006600600066a0500066b0600066d0200067008000671020006d6080006dd060006de0d0006df080006e502" ++
  "0006e7080006e90d0006ea080006ee020006f0030006fa0200071108000712020007300800074b020007a6080007b102" ++
  "0007c0010007eb080007f4010007f60d0007fa010007fd080007fe010008160800081a0100081b080008240100082508" ++
  "000828010008290800082e010008590800085c010008600200086b010008700200088f01000890060008920100089708" ++
  "0008a0020008ca080008e2060008e3080009030000093a0800093b0000093c0800093d00000941080009490000094d08" ++
  "00094e000009510800095800000962080009640000098108000982000009bc080009bd000009c1080009c5000009cd08" ++
  "0009ce000009e2080009e4000009f2050009f4000009fb050009fc000009fe080009ff00000a0108000a0300000a3c08" ++
  "000a3d00000a4108000a4300000a4708000a4900000a4b08000a4e00000a5108000a5200000a7008000a7200000a7508" ++
  "000a7600000a8108000a8300000abc08000abd00000ac108000ac600000ac708000ac900000acd08000ace00000ae208" ++
  "000ae400000af105000af200000afa08000b0000000b0108000b0200000b3c08000b3d00000b3f08000b4000000b4108" ++
  "000b4500000b4d08000b4e00000b5508000b5700000b6208000b6400000b8208000b8300000bc008000bc100000bcd08" ++
  "000bce00000bf30d000bf905000bfa0d000bfb00000c0008000c0100000c0408000c0500000c3c08000c3d00000c3e08" ++
  "000c4100000c4608000c4900000c4a08000c4e00000c5508000c5700000c6208000c6400000c780d000c7f00000c8108" ++
  "000c8200000cbc08000cbd00000ccc08000cce00000ce208000ce400000d0008000d0200000d3b08000d3d00000d4108" ++
  "000d4500000d4d08000d4e00000d6208000d6400000d8108000d8200000dca08000dcb00000dd208000dd500000dd608" ++
  "000dd700000e3108000e3200000e3408000e3b00000e3f05000e4000000e4708000e4f00000eb108000eb200000eb408" ++
  "000ebd00000ec808000ecf00000f1808000f1a00000f3508000f3600000f3708000f3800000f3908000f3a0d000f3e00" ++
  "000f7108000f7f00000f8008000f8500000f8608000f8800000f8d08000f9800000f9908000fbd00000fc608000fc700" ++
  "00102d080010310000103208001038000010390800103b0000103d0800103f000010580800105a0000105e0800106100" ++
  "00107108001075000010820800108300001085080010870000108d0800108e0000109d0800109e0000135d0800136000" ++
  "0013900d00139a000014000d001401000016800c0016810000169b0d00169d0000171208001715000017320800173400" ++
  "001752080017540000177208001774000017b4080017b6000017b7080017be000017c6080017c7000017c9080017d400" ++
  "0017db050017dc000017dd080017de000017f00d0017fa000018000d00180b0800180e0900180f080018100000188508" ++
  "001887000018a9080018aa000019200800192300001927080019290000193208001933000019390800193c000019400d" ++
  "001941000019440d001946000019de0d001a0000001a1708001a1900001a1b08001a1c00001a5608001a5700001a5808" ++
  "001a5f00001a6008001a6100001a6208001a6300001a6508001a6d00001a7308001a7d00001a7f08001a8000001ab008" ++
  "001acf00001b0008001b0400001b3408001b3500001b3608001b3b00001b3c08001b3d00001b4208001b4300001b6b08" ++
  "001b7400001b8008001b8200001ba208001ba600001ba808001baa00001bab08001bae00001be608001be700001be808" ++
  "001bea00001bed08001bee00001bef08001bf200001c2c08001c3400001c3608001c3800001cd008001cd300001cd408" ++
  "001ce100001ce208001ce900001ced08001cee00001cf408001cf500001cf808001cfa00001dc008001e0000001fbd0d" ++
  "001fbe00001fbf0d001fc200001fcd0d001fd000001fdd0d001fe000001fed0d001ff000001ffd0d001fff000020000c" ++
  "00200b0900200e0000200f010020100d0020280c0020290a00202a0e00202b1000202c1200202d0f00202e1100202f07" ++
  "002030050020350d002044070020450d00205f0c00206009002065000020661300206714002068150020691600206a09" ++
  "00207003002071000020740300207a0400207c0d00207f000020800300208a0400208c0d00208f000020a0050020d008" ++
  "0020f1000021000d002102000021030d002107000021080d00210a000021140d002115000021160d0021190000211e0d" ++
  "002124000021250d002126000021270d002128000021290d00212a0000212e0500212f0000213a0d00213c000021400d" ++
  "0021450000214a0d00214e000021500d002160000021890d00218c000021900d00221204002213050022140d00233600" ++
  "00237b0d002395000023960d00242a000024400d00244b000024600d0024880300249c000024ea0d0026ac000026ad0d" ++
  "002800000029000d002b7400002b760d002b9600002b970d002c0000002ce50d002ceb00002cef08002cf200002cf90d" ++
  "002d0000002d7f08002d8000002de008002e000d002e5e00002e800d002e9a00002e9b0d002ef400002f000d002fd600" ++
  "002ff00d0030000c0030010d003005000030080d0030210000302a0800302e000030300d003031000030360d00303800" ++
  "00303d0d003040000030990800309b0d00309d000030a00d0030a1000030fb0d0030fc000031c00d0031e6000031ef0d" ++
  "0031f00000321d0d00321f000032500d0032600000327c0d00327f000032b10d0032c0000032cc0d0032d0000033770d" ++
  "00337b000033de0d0033e0000033ff0d00340000004dc00d004e000000a4900d00a4c70000a60d0d00a6100000a66f08" ++
  "00a6730d00a6740800a67e0d00a6800000a69e0800a6a00000a6f00800a6f20000a7000d00a7220000a7880d00a78900" ++
  "00a8020800a8030000a8060800a8070000a80b0800a80c0000a8250800a8270000a8280d00a82c0800a82d0000a83805" ++
  "00a83a0000a8740d00a8780000a8c40800a8c60000a8e00800a8f20000a8ff0800a9000000a9260800a92e0000a94708" ++
  "00a9520000a9800800a9830000a9b30800a9b40000a9b60800a9ba0000a9bc0800a9be0000a9e50800a9e60000aa2908" ++
  "00aa2f0000aa310800aa330000aa350800aa370000aa430800aa440000aa4c0800aa4d0000aa7c0800aa7d0000aab008" ++
  "00aab10000aab20800aab50000aab70800aab90000aabe0800aac00000aac10800aac20000aaec0800aaee0000aaf608" ++
  "00aaf70000ab6a0d00ab6c0000abe50800abe60000abe80800abe90000abed0800abee0000fb1d0100fb1e0800fb1f01" ++
  "00fb290400fb2a0100fb500200fd3e0d00fd500200fdcf0d00fdd00000fdf00200fdfd0d00fe000800fe100d00fe1a00" ++
  "00fe200800fe300d00fe500700fe510d00fe520700fe530000fe540d00fe550700fe560d00fe5f0500fe600d00fe6204" ++
  "00fe640d00fe670000fe680d00fe690500fe6b0d00fe6c0000fe700200feff0900ff000000ff010d00ff030500ff060d" ++
  "00ff0b0400ff0c0700ff0d0400ff0e0700ff100300ff1a0700ff1b0d00ff210000ff3b0d00ff410000ff5b0d00ff6600" ++
  "00ffe00500ffe20d00ffe50500ffe70000ffe80d00ffef0000fff90d00fffe000101010d010102000101400d01018d00" ++
  "0101900d01019d000101a00d0101a1000101fd080101fe000102e0080102e1030102fc000103760801037b0001080001" ++
  "01091f0d01092001010a0108010a0401010a0508010a0701010a0c08010a1001010a3808010a3b01010a3f08010a4001" ++
  "010ae508010ae701010b390d010b4001010d0002010d2408010d2801010d3006010d3a01010d4006010d4a01010d6908" ++
  "010d6e0d010d6f01010e6006010e7f01010eab08010ead01010ec202010ec501010efc08010f0001010f3002010f4608" ++
  "010f5102010f5a01010f8208010f860101100000011001080110020001103808011047000110520d0110660001107008" ++
  "01107100011073080110750001107f08011082000110b3080110b7000110b9080110bb000110c2080110c30001110008" ++
  "011103000111270801112c0001112d0801113500011173080111740001118008011182000111b6080111bf000111c908" ++
  "0111cd000111cf080111d00001122f08011232000112340801123500011236080112380001123e0801123f0001124108" ++
  "011242000112df080112e0000112e3080112eb00011300080113020001133b0801133d00011340080113410001136608" ++
  "01136d0001137008011375000113bb080113c1000113ce080113cf000113d0080113d1000113d2080113d3000113e108" ++
  "0113e30001143808011440000114420801144500011446080114470001145e0801145f000114b3080114b9000114ba08" ++
  "0114bb000114bf080114c1000114c2080114c4000115b2080115b6000115bc080115be000115bf080115c1000115dc08" ++
  "0115de000116330801163b0001163d0801163e0001163f08011641000116600d01166d000116ab080116ac000116ad08" ++
  "0116ae000116b0080116b6000116b7080116b80001171d0801171e0001171f0801172000011722080117260001172708" ++
  "01172c0001182f08011838000118390801183b0001193b0801193d0001193e0801193f0001194308011944000119d408" ++
  "0119d8000119da080119dc000119e0080119e100011a0108011a0700011a0908011a0b00011a3308011a3900011a3b08" ++
  "011a3f00011a4708011a4800011a5108011a5700011a5908011a5c00011a8a08011a9700011a9808011a9a00011c3008" ++
  "011c3700011c3808011c3e00011c9208011ca800011caa08011cb100011cb208011cb400011cb508011cb700011d3108" ++
  "011d3700011d3a08011d3b00011d3c08011d3e00011d3f08011d4600011d4708011d4800011d9008011d9200011d9508" ++
  "011d9600011d9708011d9800011ef308011ef500011f0008011f0200011f3608011f3b00011f4008011f4100011f4208" ++
  "011f4300011f5a08011f5b00011fd50d011fdd05011fe10d011ff2000134400801344100013447080134560001611e08" ++
  "01612a0001612d0801613000016af008016af500016b3008016b3700016f4f08016f5000016f8f08016f9300016fe20d" ++
  "016fe300016fe408016fe50001bc9d0801bc9f0001bca00901bca40001cc000d01ccd60001ccf00301ccfa0001cd000d" ++
  "01ceb40001cf000801cf2e0001cf300801cf470001d1670801d16a0001d1730901d17b0801d1830001d1850801d18c00" ++
  "01d1aa0801d1ae0001d1e90d01d1eb0001d2000d01d2420801d2450d01d2460001d3000d01d3570001d6c10d01d6c200" ++
  "01d6db0d01d6dc0001d6fb0d01d6fc0001d7150d01d7160001d7350d01d7360001d74f0d01d7500001d76f0d01d77000" ++
  "01d7890d01d78a0001d7a90d01d7aa0001d7c30d01d7c40001d7ce0301d8000001da000801da370001da3b0801da6d00" ++
  "01da750801da760001da840801da850001da9b0801daa00001daa10801dab00001e0000801e0070001e0080801e01900" ++
  "01e01b0801e0220001e0230801e0250001e0260801e02b0001e08f0801e0900001e1300801e1370001e2ae0801e2af00" ++
  "01e2ec0801e2f00001e2ff0501e3000001e4ec0801e4f00001e5ee0801e5f00001e8000101e8d00801e8d70101e94408" ++
  "01e94b0101ec710201ecb50101ed010201ed3e0101ee000201eef00d01eef20201ef000101f0000d01f02c0001f0300d" ++
  "01f0940001f0a00d01f0af0001f0b10d01f0c00001f0c10d01f0d00001f0d10d01f0f60001f1000301f10b0d01f11000" ++
  "01f12f0d01f1300001f16a0d01f1700001f1ad0d01f1ae0001f2600d01f2660001f3000d01f6d80001f6dc0d01f6ed00" ++
  "01f6f00d01f6fd0001f7000d01f7770001f77b0d01f7da0001f7e00d01f7ec0001f7f00d01f7f10001f8000d01f80c00" ++
  "01f8100d01f8480001f8500d01f85a0001f8600d01f8880001f8900d01f8ae0001f8b00d01f8bc0001f8c00d01f8c200" ++
  "01f9000d01fa540001fa600d01fa6e0001fa700d01fa7d0001fa800d01fa8a0001fa8f0d01fac70001face0d01fadd00" ++
  "01fadf0d01faea0001faf00d01faf90001fb000d01fb930001fb940d01fbf00301fbfa000e0001090e0002000e002009" ++
  "0e0080000e0100080e01f000"

/-- unicode-bidi 0.3.18 `bidi_pairs_table`, in table order: 64 records of
`open:u24 close:u24 skeleton:u24` (skeleton = canonical opening bracket), hex. -/
def bracketHex : String :=
  "00002800002900002800005b00005d00005b00007b00007d00007b000f3a000f3b000f3a000f3c000f3d000f3c00169b" ++
  "00169c00169b00204500204600204500207d00207e00207d00208d00208e00208d00230800230900230800230a00230b" ++
  "00230a00232900232a00300800276800276900276800276a00276b00276a00276c00276d00276c00276e00276f00276e" ++
  "0027700027710027700027720027730027720027740027750027740027c50027c60027c50027e60027e70027e60027e8" ++
  "0027e90027e80027ea0027eb0027ea0027ec0027ed0027ec0027ee0027ef0027ee002983002984002983002985002986" ++
  "00298500298700298800298700298900298a00298900298b00298c00298b00298d00299000298d00298f00298e00298f" ++
  "0029910029920029910029930029940029930029950029960029950029970029980029970029d80029d90029d80029da" ++
  "0029db0029da0029fc0029fd0029fc002e22002e23002e22002e24002e25002e24002e26002e27002e26002e28002e29" ++
  "002e28002e55002e56002e55002e57002e58002e57002e59002e5a002e59002e5b002e5c002e5b003008003009003008" ++
  "00300a00300b00300a00300c00300d00300c00300e00300f00300e003010003011003010003014003015003014003016" ++
  "00301700301600301800301900301800301a00301b00301a00fe5900fe5a00fe5900fe5b00fe5c00fe5b00fe5d00fe5e" ++
  "00fe5d00ff0800ff0900ff0800ff3b00ff3d00ff3b00ff5b00ff5d00ff5b00ff5f00ff6000ff5f00ff6200ff6300ff62"

/-- harfrust 0.12.0 `_hb_ucd_bmg` expanded: 428 records of `cp:u24 mirror:u24`,
sorted by `cp`, hex. -/
def mirrorHex : String :=
  "00002800002900002900002800003c00003e00003e00003c00005b00005d00005d00005b00007b00007d00007d00007b" ++
  "0000ab0000bb0000bb0000ab000f3a000f3b000f3b000f3a000f3c000f3d000f3d000f3c00169b00169c00169c00169b" ++
  "00203900203a00203a00203900204500204600204600204500207d00207e00207e00207d00208d00208e00208e00208d" ++
  "00220800220b00220900220c00220a00220d00220b00220800220c00220900220d00220a0022150029f500221f002bfe" ++
  "0022200029a300222100299b0022220029a0002224002aee00223c00223d00223d00223c0022430022cd00224500224c" ++
  "00224c002245002252002253002253002252002254002255002255002254002264002265002265002264002266002267" ++
  "00226700226600226800226900226900226800226a00226b00226b00226a00226e00226f00226f00226e002270002271" ++
  "002271002270002272002273002273002272002274002275002275002274002276002277002277002276002278002279" ++
  "00227900227800227a00227b00227b00227a00227c00227d00227d00227c00227e00227f00227f00227e002280002281" ++
  "002281002280002282002283002283002282002284002285002285002284002286002287002287002286002288002289" ++
  "00228900228800228a00228b00228b00228a00228f00229000229000228f0022910022920022920022910022980029b8" ++
  "0022a20022a30022a30022a20022a6002ade0022a8002ae40022a9002ae30022ab002ae50022b00022b10022b10022b0" ++
  "0022b20022b30022b30022b20022b40022b50022b50022b40022b60022b70022b70022b60022b80027dc0022c90022ca" ++
  "0022ca0022c90022cb0022cc0022cc0022cb0022cd0022430022d00022d10022d10022d00022d60022d70022d70022d6" ++
  "0022d80022d90022d90022d80022da0022db0022db0022da0022dc0022dd0022dd0022dc0022de0022df0022df0022de" ++
  "0022e00022e10022e10022e00022e20022e30022e30022e20022e40022e50022e50022e40022e60022e70022e70022e6" ++
  "0022e80022e90022e90022e80022ea0022eb0022eb0022ea0022ec0022ed0022ed0022ec0022f00022f10022f10022f0" ++
  "0022f20022fa0022f30022fb0022f40022fc0022f60022fd0022f70022fe0022fa0022f20022fb0022f30022fc0022f4" ++
  "0022fd0022f60022fe0022f700230800230900230900230800230a00230b00230b00230a00232900232a00232a002329" ++
  "00276800276900276900276800276a00276b00276b00276a00276c00276d00276d00276c00276e00276f00276f00276e" ++
  "0027700027710027710027700027720027730027730027720027740027750027750027740027c30027c40027c40027c3" ++
  "0027c50027c60027c60027c50027c80027c90027c90027c80027cb0027cd0027cd0027cb0027d50027d60027d60027d5" ++
  "0027dc0022b80027dd0027de0027de0027dd0027e20027e30027e30027e20027e40027e50027e50027e40027e60027e7" ++
  "0027e70027e60027e80027e90027e90027e80027ea0027eb0027eb0027ea0027ec0027ed0027ed0027ec0027ee0027ef" ++
  "0027ef0027ee00298300298400298400298300298500298600298600298500298700298800298800298700298900298a" ++
  "00298a00298900298b00298c00298c00298b00298d00299000298e00298f00298f00298e00299000298d002991002992" ++
  "00299200299100299300299400299400299300299500299600299600299500299700299800299800299700299b002221" ++
  "0029a00022220029a30022200029a40029a50029a50029a40029a80029a90029a90029a80029aa0029ab0029ab0029aa" ++
  "0029ac0029ad0029ad0029ac0029ae0029af0029af0029ae0029b80022980029c00029c10029c10029c00029c40029c5" ++
  "0029c50029c40029cf0029d00029d00029cf0029d10029d20029d20029d10029d40029d50029d50029d40029d80029d9" ++
  "0029d90029d80029da0029db0029db0029da0029e80029e90029e90029e80029f50022150029f80029f90029f90029f8" ++
  "0029fc0029fd0029fd0029fc002a2b002a2c002a2c002a2b002a2d002a2e002a2e002a2d002a34002a35002a35002a34" ++
  "002a3c002a3d002a3d002a3c002a64002a65002a65002a64002a79002a7a002a7a002a79002a7b002a7c002a7c002a7b" ++
  "002a7d002a7e002a7e002a7d002a7f002a80002a80002a7f002a81002a82002a82002a81002a83002a84002a84002a83" ++
  "002a85002a86002a86002a85002a87002a88002a88002a87002a89002a8a002a8a002a89002a8b002a8c002a8c002a8b" ++
  "002a8d002a8e002a8e002a8d002a8f002a90002a90002a8f002a91002a92002a92002a91002a93002a94002a94002a93" ++
  "002a95002a96002a96002a95002a97002a98002a98002a97002a99002a9a002a9a002a99002a9b002a9c002a9c002a9b" ++
  "002a9d002a9e002a9e002a9d002a9f002aa0002aa0002a9f002aa1002aa2002aa2002aa1002aa6002aa7002aa7002aa6" ++
  "002aa8002aa9002aa9002aa8002aaa002aab002aab002aaa002aac002aad002aad002aac002aaf002ab0002ab0002aaf" ++
  "002ab1002ab2002ab2002ab1002ab3002ab4002ab4002ab3002ab5002ab6002ab6002ab5002ab7002ab8002ab8002ab7" ++
  "002ab9002aba002aba002ab9002abb002abc002abc002abb002abd002abe002abe002abd002abf002ac0002ac0002abf" ++
  "002ac1002ac2002ac2002ac1002ac3002ac4002ac4002ac3002ac5002ac6002ac6002ac5002ac7002ac8002ac8002ac7" ++
  "002ac9002aca002aca002ac9002acb002acc002acc002acb002acd002ace002ace002acd002acf002ad0002ad0002acf" ++
  "002ad1002ad2002ad2002ad1002ad3002ad4002ad4002ad3002ad5002ad6002ad6002ad5002ade0022a6002ae30022a9" ++
  "002ae40022a8002ae50022ab002aec002aed002aed002aec002aee002224002af7002af8002af8002af7002af9002afa" ++
  "002afa002af9002bfe00221f002e02002e03002e03002e02002e04002e05002e05002e04002e09002e0a002e0a002e09" ++
  "002e0c002e0d002e0d002e0c002e1c002e1d002e1d002e1c002e20002e21002e21002e20002e22002e23002e23002e22" ++
  "002e24002e25002e25002e24002e26002e27002e27002e26002e28002e29002e29002e28002e55002e56002e56002e55" ++
  "002e57002e58002e58002e57002e59002e5a002e5a002e59002e5b002e5c002e5c002e5b003008003009003009003008" ++
  "00300a00300b00300b00300a00300c00300d00300d00300c00300e00300f00300f00300e003010003011003011003010" ++
  "00301400301500301500301400301600301700301700301600301800301900301900301800301a00301b00301b00301a" ++
  "00fe5900fe5a00fe5a00fe5900fe5b00fe5c00fe5c00fe5b00fe5d00fe5e00fe5e00fe5d00fe6400fe6500fe6500fe64" ++
  "00ff0800ff0900ff0900ff0800ff1c00ff1e00ff1e00ff1c00ff3b00ff3d00ff3d00ff3b00ff5b00ff5d00ff5d00ff5b" ++
  "00ff5f00ff6000ff6000ff5f00ff6200ff6300ff6300ff62"

-- END GENERATED

/-! ## Table decoding -/

/-- Value of one hex digit (`0` for anything else). -/
def hexDigit (c : Char) : Nat :=
  if '0' ≤ c ∧ c ≤ '9' then c.toNat - '0'.toNat
  else if 'a' ≤ c ∧ c ≤ 'f' then c.toNat - 'a'.toNat + 10
  else 0

/-- Decode a hex string made of fixed-layout records into a flat array of
fields: `widths` gives each field's width in hex digits; the result holds
`widths.size` numbers per record. A trailing partial record is dropped. -/
def decodeHex (s : String) (widths : Array Nat) : Array Nat := Id.run do
  let cs := s.toList.toArray
  let rec_ := widths.foldl (· + ·) 0
  if rec_ == 0 then return #[]
  let n := cs.size / rec_
  let mut out : Array Nat := Array.mkEmpty (n * widths.size)
  let mut pos := 0
  for _ in [0:n] do
    for w in widths do
      let mut v := 0
      for j in [0:w] do
        v := v * 16 + hexDigit (cs.getD (pos + j) '0')
      out := out.push v
      pos := pos + w
  return out

/-- Class table: pairs `start, classIndex`, sorted by `start`, first `start = 0`. -/
def classTable : Array Nat := decodeHex classHex #[6, 2]

/-- Bracket table: triples `open, close, skeleton`, in the crate's order. -/
def bracketTable : Array Nat := decodeHex bracketHex #[6, 6, 6]

/-- Mirroring table: pairs `cp, mirror`, sorted by `cp`. -/
def mirrorTable : Array Nat := decodeHex mirrorHex #[6, 6]

/-- Index of the last record (of `stride` fields, key in field 0) whose key is
`≤ key`, or `none`: a binary search with a fixed 32-step bound. -/
def searchLE (tbl : Array Nat) (stride key : Nat) : Option Nat := Id.run do
  let n := tbl.size / stride
  -- invariant: records `< lo` have key `≤ key`, records `≥ hi` have key `> key`
  let mut lo := 0
  let mut hi := n
  for _ in [0:32] do
    if lo < hi then
      let mid := (lo + hi) / 2
      if tbl.getD (mid * stride) 0 ≤ key then lo := mid + 1 else hi := mid
  if lo == 0 then none else some (lo - 1)

/-- `Bidi_Class` of `cp` per unicode-bidi 0.3.18 (`L` when unlisted). -/
def bidiClass (cp : Nat) : Cls :=
  match searchLE classTable 2 cp with
  | some k => clsOfIndex (classTable.getD (2 * k + 1) 0)
  | none => .L

/-- Bidi_Mirroring_Glyph of `cp` as harfrust 0.12.0 has it, or `none`. -/
def mirror (cp : Nat) : Option Nat :=
  match searchLE mirrorTable 2 cp with
  | some k => if mirrorTable.getD (2 * k) 0 == cp then some (mirrorTable.getD (2 * k + 1) 0) else none
  | none => none

/-- The crate's `bidi_matched_opening_bracket`: the first bracket-table entry
with `cp` as its opening or closing bracket, as `(skeleton opening bracket,
isOpening)`. -/
def matchedBracket (cp : Nat) : Option (Nat × Bool) := Id.run do
  for k in [0:bracketTable.size / 3] do
    let o := bracketTable.getD (3 * k) 0
    let c := bracketTable.getD (3 * k + 1) 0
    if o == cp || c == cp then
      return some (bracketTable.getD (3 * k + 2) 0, o == cp)
  return none

/-! ## Initial classes and explicit levels (P2/X5c, X1–X8) -/

/-- Original classes with each `FSI` rewritten to `LRI`/`RLI` by the first
strong character directly inside it (X5c, as `compute_initial_info` does it:
only the innermost open isolate is examined), plus the crate's `is_pure_ltr`
and `has_isolate_controls` flags. -/
def initialClasses (cps : Array Nat) : Array Cls × Bool := Id.run do
  let mut cls : Array Cls := Array.mkEmpty cps.size
  let mut iso : Array Nat := #[]
  let mut pureLtr := true
  for cp in cps do
    let c := bidiClass cp
    let i := cls.size
    cls := cls.push c
    match c with
    | .L | .R | .AL =>
      if c != .L then pureLtr := false
      match iso.back? with
      | some st =>
        if cls.getD st .L == .FSI then
          cls := cls.setIfInBounds st (if c == .L then .LRI else .RLI)
      | none => pure ()
    | .AN | .LRE | .RLE | .LRO | .RLO => pureLtr := false
    | .RLI | .LRI | .FSI =>
      pureLtr := false
      iso := iso.push i
    | .PDI => iso := iso.pop
    | _ => pure ()
  return (cls, pureLtr)

/-- Apply an override status (1 = RTL, 2 = LTR) to a processing class. -/
def overrideCls (st : Nat) (c : Cls) : Cls :=
  if st == 1 then .R else if st == 2 then .L else c

/-- X1–X8 (`explicit::compute`): explicit levels, processing classes, and the
level runs (BD7, X9-removed characters never start a run) as `(start, stop)`.
Stack entries are `(level, status)` with status 0 = neutral, 1 = RTL
override, 2 = LTR override, 3 = isolate. -/
def explicitLevels (cls : Array Cls) (para : Nat) :
    Array Nat × Array Cls × Array (Nat × Nat) := Id.run do
  let n := cls.size
  let mut lv := Array.replicate n para
  let mut pc := cls
  let mut stack : Array (Nat × Nat) := #[(para, 0)]
  let mut ovIso := 0
  let mut ovEmb := 0
  let mut validIso := 0
  let mut runs : Array (Nat × Nat) := #[]
  let mut runLevel := 0
  let mut runStart := 0
  for i in [0:n] do
    let c := cls.getD i .L
    let (lastLv, lastSt) := stack.back?.getD (para, 0)
    match c with
    | .RLE | .LRE | .RLO | .LRO | .RLI | .LRI | .FSI =>
      lv := lv.setIfInBounds i lastLv
      let iso := isIsoInit c
      if iso then pc := pc.modify i (overrideCls lastSt)
      let rtl := c == .RLE || c == .RLO || c == .RLI
      let newLv := if rtl then (if lastLv % 2 == 0 then lastLv + 1 else lastLv + 2)
                   else (if lastLv % 2 == 0 then lastLv + 2 else lastLv + 1)
      if newLv ≤ 125 && ovIso == 0 && ovEmb == 0 then
        let st := if c == .RLO then 1 else if c == .LRO then 2 else if iso then 3 else 0
        stack := stack.push (newLv, st)
        if iso then validIso := validIso + 1 else lv := lv.setIfInBounds i newLv
      else if iso then ovIso := ovIso + 1
      else if ovIso == 0 then ovEmb := ovEmb + 1
      if !iso then pc := pc.setIfInBounds i .BN
    | .PDI =>
      if ovIso > 0 then ovIso := ovIso - 1
      else if validIso > 0 then
        ovEmb := 0
        for _ in [0:stack.size] do
          match stack.back? with
          | none => break
          | some (_, st) =>
            stack := stack.pop
            if st == 3 then break
        validIso := validIso - 1
      let (l2, s2) := stack.back?.getD (para, 0)
      lv := lv.setIfInBounds i l2
      pc := pc.modify i (overrideCls s2)
    | .PDF =>
      if ovIso > 0 then pure ()
      else if ovEmb > 0 then ovEmb := ovEmb - 1
      else if lastSt != 3 && stack.size ≥ 2 then stack := stack.pop
      lv := lv.setIfInBounds i (stack.back?.getD (para, 0)).1
      pc := pc.setIfInBounds i .BN
    | .B => pure ()
    | _ =>
      lv := lv.setIfInBounds i lastLv
      if c != .BN then pc := pc.modify i (overrideCls lastSt)
    let li := lv.getD i 0
    if i == 0 then runLevel := li
    else if !removedX9 c && li != runLevel then
      runs := runs.push (runStart, i)
      runLevel := li
      runStart := i
  if n > runStart then runs := runs.push (runStart, n)
  return (lv, pc, runs)

/-! ## Isolating run sequences (BD13, X10) -/

/-- BD13: group level runs (indices into `runs`) into isolating run
sequences, as `prepare::isolating_run_sequences` does (the order of the
sequences is irrelevant: each is resolved independently). -/
def runSequences (cls : Array Cls) (runs : Array (Nat × Nat)) : Array (Array Nat) := Id.run do
  let mut stack : Array (Array Nat) := #[#[]]
  let mut seqs : Array (Array Nat) := #[]
  for r in [0:runs.size] do
    let (a, b) := runs.getD r (0, 0)
    let startC := cls.getD a .L
    let mut endC := startC
    for k in [0:b - a] do
      let c := cls.getD (b - 1 - k) .L
      if !removedX9 c then
        endC := c
        break
    let mut seq : Array Nat := #[]
    if startC == .PDI && stack.size > 1 then
      seq := stack.back?.getD #[]
      stack := stack.pop
    seq := seq.push r
    if isIsoInit endC then stack := stack.push seq else seqs := seqs.push seq
  for k in [0:stack.size] do
    let s := stack.getD (stack.size - 1 - k) #[]
    if !s.isEmpty then seqs := seqs.push s
  return seqs

/-! ## Walking a sequence backwards -/

/-- Fold `f` over sequence positions in the order of the crate's
`iter_backwards_from` for position `p` in level run `r`: `p-1` down to the
start of run `r`, then each earlier run from the last to the first, but each
of those *ascending* (the crate chains `prev_runs.iter().rev()
.flat_map(Clone::clone)`; this matters when the scan reaches an earlier
run). `rsp[k]` is the first position of run `k`, `rsp[runs]` the sequence
length. `f` returns the new state and whether to go on. -/
def backScan {σ : Type} (rsp : Array Nat) (r p : Nat) (init : σ)
    (f : σ → Nat → σ × Bool) : σ := Id.run do
  let mut st := init
  for k in [0:p - rsp.getD r 0] do
    let (st', go) := f st (p - 1 - k)
    st := st'
    if !go then return st
  for rr in [0:r] do
    let q := r - 1 - rr
    for pos in [rsp.getD q 0:rsp.getD (q + 1) 0] do
      let (st', go) := f st pos
      st := st'
      if !go then return st
  return st

/-- Set every `BN` met by `backScan` from position `p` (run `r`) to `v`,
stopping at the first non-`BN`. -/
def backFillBN (s rsp : Array Nat) (r p : Nat) (v : Cls) (pc : Array Cls) : Array Cls :=
  backScan rsp r p pc fun pc pos =>
    let j := s.getD pos 0
    if pc.getD j .L != .BN then (pc, false) else (pc.setIfInBounds j v, true)

/-! ## Weak types (W1–W7) -/

/-- W1–W7 on one isolating run sequence (`resolve_weak`), given its
characters `s` in order, `runOf[p]` the level run of position `p` and `rsp`
the runs' start positions (see `backScan`). -/
def resolveWeak (s runOf rsp : Array Nat) (sos eos : Cls) (pc0 : Array Cls) :
    Array Cls := Id.run do
  let mut pc := pc0
  let mut prevW4 := sos
  let mut prevW5 := sos
  let mut prevW1 := sos
  let mut lastAL := false
  let mut et : Array Nat := #[]
  let mut bn : Array Nat := #[]
  for p in [0:s.size] do
    let i := s.getD p 0
    if pc.getD i .L == .BN then
      bn := bn.push i
      continue
    let mut w2 := pc.getD i .L
    -- W1
    if w2 == .NSM then
      let v := if isIsoInit prevW1 || prevW1 == .PDI then .ON else prevW1
      pc := pc.setIfInBounds i v
      w2 := v
    prevW1 := pc.getD i .L
    -- W2, W3
    match pc.getD i .L with
    | .EN => if lastAL then pc := pc.setIfInBounds i .AN
    | .AL => pc := pc.setIfInBounds i .R
    | _ => pure ()
    match w2 with
    | .L | .R => lastAL := false
    | .AL => lastAL := true
    | _ => pure ()
    let c456 := pc.getD i .L
    -- W4, W5, W6 (separators, terminators)
    match c456 with
    | .EN =>
      for j in et do pc := pc.setIfInBounds j .EN
      et := #[]
    | .ES | .CS =>
      let mut next := eos
      for q in [p + 1:s.size] do
        let c := pc.getD (s.getD q 0) .L
        if !removedX9 c then
          next := c
          break
      if next == .EN && lastAL then next := .AN
      let v := if prevW4 == .EN && next == .EN then .EN
               else if prevW4 == .AN && c456 == .CS && next == .AN then .AN
               else .ON
      pc := pc.setIfInBounds i v
      if v == .ON then
        pc := backFillBN s rsp (runOf.getD p 0) p .ON pc
        for q in [p + 1:s.size] do
          let j := s.getD q 0
          if pc.getD j .L != .BN then break
          pc := pc.setIfInBounds j .ON
    | .ET =>
      if prevW5 == .EN then pc := pc.setIfInBounds i .EN
      else
        et := et ++ bn
        et := et.push i
    | _ => pure ()
    bn := #[]
    prevW5 := pc.getD i .L
    if prevW5 != .ET then
      for j in et do pc := pc.setIfInBounds j .ON
      et := #[]
    prevW4 := c456
  for j in et do pc := pc.setIfInBounds j .ON
  -- W7
  let mut lastL := sos == .L
  for i in s do
    match pc.getD i .L with
    | .EN => if lastL then pc := pc.setIfInBounds i .L
    | .L => lastL := true
    | .R | .AL => lastL := false
    | _ => pure ()
  return pc

/-! ## Neutral types (N0–N2) -/

/-- BD16 as `identify_bracket_pairs` does it: for each sequence position of an
opening bracket that has a match, `1 + ` the position of its closing bracket
(`0` = unpaired). Only characters whose processing class is `ON` count. On
stack overflow (63 entries) the rest of the current *level run* is skipped
(the crate `break`s its inner loop only). `runOf[p]` is the level run of
sequence position `p`. -/
def bracketPairs (cps : Array Nat) (s runOf : Array Nat) (pc : Array Cls) : Array Nat := Id.run do
  let mut closeAt := Array.replicate s.size 0
  let mut stack : Array (Nat × Nat) := #[]   -- (skeleton, position)
  let mut skipRun := 0                        -- 1 + run being skipped, 0 = none
  for p in [0:s.size] do
    let i := s.getD p 0
    let r := runOf.getD p 0
    if skipRun == r + 1 then continue
    if pc.getD i .L != .ON then continue
    match matchedBracket (cps.getD i 0) with
    | none => pure ()
    | some (sk, isOpen) =>
      if isOpen then
        if stack.size ≥ 63 then
          skipRun := r + 1
        else
          stack := stack.push (sk, p)
      else
        for k in [0:stack.size] do
          let idx := stack.size - 1 - k
          let (sk2, q) := stack.getD idx (0, 0)
          if sk2 == sk then
            closeAt := closeAt.setIfInBounds q (p + 1)
            stack := stack.take idx
            break
  return closeAt

/-- N0–N2 on one isolating run sequence (`resolve_neutral`). `e` is the
embedding direction of the sequence's first character's level. -/
def resolveNeutral (cps : Array Nat) (s runOf rsp : Array Nat) (sos eos e : Cls)
    (orig : Array Cls) (pc0 : Array Cls) : Array Cls := Id.run do
  let mut pc := pc0
  let notE := if e == .L then Cls.R else Cls.L
  let closeAt := bracketPairs cps s runOf pc
  -- N0, pairs in order of their opening bracket
  for po in [0:s.size] do
    let pcl := closeAt.getD po 0
    if pcl == 0 then continue
    let pclose := pcl - 1
    let mut foundE := false
    let mut foundNotE := false
    for q in [po + 1:pclose] do
      let c := pc.getD (s.getD q 0) .L
      if c == e then foundE := true
      else if c == notE then foundNotE := true
      else if c == .EN || c == .AN then
        if e == .L then foundNotE := true else foundE := true
      if foundE then break
    let mut set : Option Cls := none
    if foundE then set := some e
    else if foundNotE then
      let found := backScan rsp (runOf.getD po 0) po (none : Option Cls) fun _ pos =>
        let c := pc.getD (s.getD pos 0) .L
        if c == .L || c == .R || c == .EN || c == .AN then (some c, false) else (none, true)
      let prev := found.getD sos
      set := some (if prev == .EN || prev == .AN then .R else prev)
    match set with
    | none => pure ()
    | some v =>
      pc := pc.setIfInBounds (s.getD po 0) v
      pc := pc.setIfInBounds (s.getD pclose 0) v
      pc := backFillBN s rsp (runOf.getD po 0) po v pc
      for q in [po + 1:s.size] do
        let j := s.getD q 0
        if orig.getD j .L == .NSM || pc.getD j .L == .BN then pc := pc.setIfInBounds j v
        else break
      for q in [pclose + 1:s.size] do
        let j := s.getD q 0
        if orig.getD j .L == .NSM || pc.getD j .L == .BN then pc := pc.setIfInBounds j v
        else break
  -- N1, N2: runs of NI/BN take the direction of their strong neighbours, else `e`
  let resolve (prev next : Cls) : Cls :=
    let rish (c : Cls) := c == .R || c == .AN || c == .EN
    if prev == .L && next == .L then .L
    else if rish prev && rish next then .R
    else e
  let mut prev := sos
  let mut niStart := 0
  let mut inNI := false
  for p in [0:s.size] do
    let c := pc.getD (s.getD p 0) .L
    if isNI c || c == .BN then
      if !inNI then
        inNI := true
        niStart := p
    else
      if inNI then
        let v := resolve prev c
        for q in [niStart:p] do pc := pc.setIfInBounds (s.getD q 0) v
        inNI := false
      prev := c
  if inNI then
    let v := resolve prev eos
    for q in [niStart:s.size] do pc := pc.setIfInBounds (s.getD q 0) v
  return pc

/-! ## Paragraph levels -/

/-- The original classes (after X5c) and the crate's `BidiInfo.levels` for the
whole text as one paragraph with level `paraLevel` (0 or 1): explicit, weak,
neutral and implicit resolution, then `assign_levels_to_removed_chars`. Like
the crate, a pure-LTR paragraph at level 0 skips straight to all-zero levels. -/
def resolveParagraph (cps : Array Nat) (paraLevel : Nat) : Array Cls × Array Nat := Id.run do
  let para := paraLevel % 2
  let n := cps.size
  let (cls, pureLtr) := initialClasses cps
  if para == 0 && pureLtr then return (cls, Array.replicate n 0)
  let (lv0, pc0, runs) := explicitLevels cls para
  let mut lv := lv0
  let mut pc := pc0
  -- prevNR[i] = 1 + last non-removed index < i (0 = none); nextNR[i] = first ≥ i (n = none)
  let mut prevNR := Array.replicate (n + 1) 0
  for i in [0:n] do
    prevNR := prevNR.setIfInBounds (i + 1)
      (if removedX9 (cls.getD i .L) then prevNR.getD i 0 else i + 1)
  let mut nextNR := Array.replicate (n + 1) n
  for k in [0:n] do
    let i := n - 1 - k
    nextNR := nextNR.setIfInBounds i
      (if removedX9 (cls.getD i .L) then nextNR.getD (i + 1) n else i)
  for seq in runSequences cls runs do
    let mut s : Array Nat := #[]
    let mut runOf : Array Nat := #[]
    let mut rsp : Array Nat := #[]
    for r in [0:seq.size] do
      let (a, b) := runs.getD (seq.getD r 0) (0, 0)
      rsp := rsp.push s.size
      for i in [a:b] do
        s := s.push i
        runOf := runOf.push r
    rsp := rsp.push s.size
    let startSeq := s.getD 0 0
    let endSeq := s.back?.getD 0 + 1
    let mut seqLevel := lv.getD startSeq 0
    for i in s do
      if !removedX9 (cls.getD i .L) then
        seqLevel := lv.getD i 0
        break
    let mut endLevel := lv.getD (endSeq - 1) 0
    for k in [0:s.size] do
      let i := s.getD (s.size - 1 - k) 0
      if !removedX9 (cls.getD i .L) then
        endLevel := lv.getD i 0
        break
    let pr := prevNR.getD startSeq 0
    let predLevel := if pr == 0 then para else lv.getD (pr - 1) 0
    let lastNR := prevNR.getD endSeq 0
    let lastCls := if lastNR == 0 then Cls.BN else cls.getD (lastNR - 1) .BN
    let nx := nextNR.getD endSeq n
    let succLevel := if isIsoInit lastCls || nx ≥ n then para else lv.getD nx 0
    let sos := levelCls (max seqLevel predLevel)
    let eos := levelCls (max endLevel succLevel)
    pc := resolveWeak s runOf rsp sos eos pc
    pc := resolveNeutral cps s runOf rsp sos eos (levelCls (lv.getD startSeq 0)) cls pc
  -- I1, I2
  for i in [0:n] do
    let l := lv.getD i 0
    let c := pc.getD i .L
    let l' := if l % 2 == 0 then
        (if c == .AN || c == .EN then l + 2 else if c == .R then l + 1 else l)
      else (if c == .L || c == .EN || c == .AN then l + 1 else l)
    lv := lv.setIfInBounds i l'
  -- assign_levels_to_removed_chars
  for i in [0:n] do
    if removedX9 (cls.getD i .L) then
      lv := lv.setIfInBounds i (if i == 0 then para else lv.getD (i - 1) 0)
  return (cls, lv)

/-- The crate's `BidiInfo.levels` (one per codepoint) for the whole text as one
paragraph with level `paraLevel`: all rules up to I2, no line rules (L1). -/
def paragraphLevels (cps : Array Nat) (paraLevel : Nat) : Array Nat :=
  (resolveParagraph cps paraLevel).2

/-! ## Line levels (L1) and visual runs (L2) -/

/-- Embedding levels, one per input codepoint: `BidiInfo::new(text, Some(level))`
with paragraph level `paraLevel` (0 = LTR, 1 = RTL), then the L1 adjustments
`reordered_levels` makes for a line spanning the whole text: trailing
whitespace / isolate controls, and each segment or paragraph separator with
the whitespace before it, reset to the paragraph level; X9-removed characters
take the (adjusted) level of the character before them. The whole input is
one paragraph (see the module docstring). -/
def levels (cps : Array Nat) (paraLevel : Nat) : Array Nat := Id.run do
  let para := paraLevel % 2
  let (cls, lv0) := resolveParagraph cps para
  let mut lv := lv0
  let n := cps.size
  let mut resetFrom := 1      -- 1 + start of the pending reset, 0 = none
  let mut resetTo := 0        -- stop of the pending reset, 0 = none
  let mut prev := para
  for i in [0:n] do
    match cls.getD i .L with
    | .B | .S =>
      resetTo := i + 1
      if resetFrom == 0 then resetFrom := i + 1
    | .WS | .FSI | .LRI | .RLI | .PDI =>
      if resetFrom == 0 then resetFrom := i + 1
    | .RLE | .LRE | .RLO | .LRO | .PDF | .BN =>
      if resetFrom == 0 then resetFrom := i + 1
      lv := lv.setIfInBounds i prev
    | _ => resetFrom := 0
    if resetFrom != 0 && resetTo != 0 then
      for j in [resetFrom - 1:resetTo] do lv := lv.setIfInBounds j para
      resetFrom := 0
      resetTo := 0
    prev := lv.getD i 0
  if resetFrom != 0 then
    for j in [resetFrom - 1:n] do lv := lv.setIfInBounds j para
  return lv

/-- L2 reordering: the runs `visual_runs` returns, as half-open logical index
ranges `(start, stop)` plus that run's (L1-adjusted) level, in visual
(left-to-right) order. Indices are codepoint indices. Empty input gives no
runs (the crate would index out of bounds). -/
def visualRuns (cps : Array Nat) (paraLevel : Nat) : Array (Nat × Nat × Nat) := Id.run do
  let lv := levels cps paraLevel
  let n := lv.size
  if n == 0 then return #[]
  let mut runs : Array (Nat × Nat × Nat) := #[]
  let mut start := 0
  let mut minL := lv.getD 0 0
  let mut maxL := minL
  for i in [1:n] do
    let l := lv.getD i 0
    if l != lv.getD start 0 then
      runs := runs.push (start, i, lv.getD start 0)
      start := i
      minL := min minL l
      maxL := max maxL l
  runs := runs.push (start, n, lv.getD start 0)
  let minOdd := minL ||| 1
  -- levels are ≤ 126, so 127 passes cover `maxL` down to `minOdd`
  for d in [0:127] do
    if d > maxL then break
    let m := maxL - d
    if m < minOdd then break
    let mut k := 0
    for _ in [0:runs.size] do
      if k ≥ runs.size then break
      if (runs.getD k (0, 0, 0)).2.2 < m then
        k := k + 1
      else
        let mut e := k + 1
        for _ in [0:runs.size] do
          if e < runs.size && (runs.getD e (0, 0, 0)).2.2 ≥ m then e := e + 1 else break
        -- reverse runs[k:e]
        for t in [0:(e - k) / 2] do
          runs := runs.swapIfInBounds (k + t) (e - 1 - t)
        k := e
  return runs

end LeanSvg.Bidi
