#!/usr/bin/env python3
"""Generate spec/README.md from the theorems in spec/*.lean.

Theorems are found by scanning the source (like scripts/axiom_audit.py).
For each one the README shows the statement (from `theorem` up to the `:=`
that starts the proof), the first sentence of its docstring, and file:line.

Every theorem must be listed in HEADLINE or HELPER below; an unlisted one
fails the script, so a new theorem gets a deliberate place in the README.

    python3 scripts/gen_spec_readme.py          # write spec/README.md
    python3 scripts/gen_spec_readme.py --check  # fail if it is stale
"""
import re
import sys
import textwrap
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SPEC = REPO / "spec"
OUT = SPEC / "README.md"

# Files in README order, with their headline theorems in the order shown.
HEADLINE: dict[str, list[str]] = {
    "Cli.lean": ["parse_paths_mem", "parse_paths_ne_empty", "parse_warnings_iff", "warnPath_ne"],
    "SizeBound.lean": [
        "render_rejects_large",
        "render_output_size_bound",
        "render_size_le_const",
        "renderWithWarnings_rejects_large",
        "renderWithWarnings_size_le",
        "encode_size_le",
        "encode_size_le_square",
    ],
    "Locality.lean": [
        "fillMask_local",
        "fillMaskShader_local",
        "compositeNormal_local",
        "compositeBlend_local",
        "fillMask_count",
        "fillMaskShader_count",
        "compositeNormal_count",
        "compositeBlend_count",
    ],
    "ImageLocality.lean": ["fillMaskImage_in_box", "fillMaskImage_local", "fillMaskImage_count"],
    "SvgImageLocality.lean": ["svgImage_in_box", "composite_local"],
    "PngDecode.lean": ["decode_size"],
    "JpegDecode.lean": ["decode_size"],
    "GifDecode.lean": ["decode_size"],
    "Gzip.lean": ["gunzip_size_le"],
    "Svg.lean": ["use_maxDepth_le"],
}

# Lemmas used to prove the headline theorems; listed by name and place only.
HELPER: dict[str, list[str]] = {
    "Cli.lean": ["parseArgs_mem", "parse_some"],
    "SizeBound.lean": [
        "forIn_invariant",
        "forIn_measure_le",
        "size_copySlice_append_le",
        "size_blockHeader",
        "size_be32",
        "size_chunk",
        "encode_size_le'",
        "storedPieces_size_le",
        "storedRows_size_le",
        "zlibStoredRows_size_le",
        "square_budget",
    ],
    "Locality.lean": ["forIn_invariant_mem", "forIn_range_invariant", "getD_setIfInBounds_ne", "inRect_count"],
    "ImageLocality.lean": ["forIn_invariant_mem", "forIn_range_invariant", "getD_setIfInBounds_ne"],
    "SvgImageLocality.lean": [
        "forIn_invariant_mem",
        "forIn_range_invariant",
        "getD_setIfInBounds_ne",
        "rowcol",
        "layerBox_sub",
    ],
}

DECL_RE = re.compile(
    r"^\s*(?:private\s+|protected\s+|noncomputable\s+)*theorem\s+"
    r"([A-Za-z_][A-Za-z0-9_.'!?]*)"
)
NAMESPACE_RE = re.compile(r"^\s*namespace\s+(\S+)")
END_RE = re.compile(r"^\s*end\b")

INTRO = """\
# Specification

What lean-svg proves about itself, in Lean, with no `sorry`. Each file here
imports the `LeanSvg` module it is about and states theorems about its
definitions. Every theorem depends on at most Lean's three standard axioms
(`propext`, `Classical.choice`, `Quot.sound`).

Trusted, not proved: the Lean kernel and compiler, Lean's `IO` primitives,
and `main` in `Main.lean`, which is short enough to read by eye.
`SPEC.md` says in prose what is promised and what is not.

Check (builds, elaborates every file here, and runs the axiom audit and the
other invariant checks):

```bash
lake build
scripts/check-theorems.sh
```

One file: `lake env lean spec/SizeBound.lean`.

There are no theorems under `LeanSvg/` (`tests/check_invariants.py` checks
this), only a few `example`s checked at build time next to the code they
test (`FamilyMatch.lean`, `Synth.lean`, `StixNonUnicode.lean`).

This file is generated by `scripts/gen_spec_readme.py` from the sources;
do not edit it by hand.
"""


def theorems(path: Path) -> list[tuple[str, int, str, str | None, str]]:
    """(name, line, statement, summary, full name) for every theorem in `path`."""
    lines = path.read_text().splitlines()
    out = []
    ns: list[str] = []
    for idx, line in enumerate(lines):
        if m := NAMESPACE_RE.match(line):
            ns.append(m.group(1))
            continue
        if END_RE.match(line):
            ns.pop()
            continue
        m = DECL_RE.match(line)
        if not m:
            continue
        full = ".".join(ns + [m.group(1)])
        out.append((m.group(1), idx + 1, statement(lines, idx), summary(lines, idx, path), full))
    return out


def statement(lines: list[str], start: int) -> str:
    """Text from `theorem` up to the first `:=` outside brackets."""
    text = "\n".join(lines[start:])
    depth = 0
    for i, ch in enumerate(text):
        if ch in "([{⟨":
            depth += 1
        elif ch in ")]}⟩":
            depth -= 1
        elif ch == ":" and depth == 0 and text[i + 1 : i + 2] == "=":
            stmt = text[:i].rstrip()
            return textwrap.dedent(stmt)
    raise SystemExit(f"{lines[start]!r}: no ':=' found")


def summary(lines: list[str], start: int, path: Path) -> str | None:
    """First sentence of the docstring just above line `start`, or None."""
    j = start - 1
    while j >= 0 and lines[j].lstrip().startswith("@["):
        j -= 1
    if j < 0 or not lines[j].rstrip().endswith("-/"):
        return None
    k = j
    while "/--" not in lines[k]:
        k -= 1
        if k < 0 or lines[k].strip().startswith("-/"):
            return None
    doc = " ".join(l.strip() for l in lines[k : j + 1])
    doc = doc.split("/--", 1)[1].rsplit("-/", 1)[0].strip().replace("**", "")
    m = re.match(r"(.+?[.!?])(\s|$)", doc)
    return m.group(1) if m else doc


def render() -> str:
    files = sorted(p.name for p in SPEC.glob("*.lean"))
    unknown = set(files) - set(HEADLINE)
    if unknown:
        raise SystemExit(f"spec files not listed in HEADLINE: {sorted(unknown)}")
    parts = [INTRO]
    for name in HEADLINE:
        path = SPEC / name
        if not path.exists():
            raise SystemExit(f"HEADLINE lists {name}, which is not in spec/")
        found = {t[0]: t for t in theorems(path)}
        head, helpers = HEADLINE[name], HELPER.get(name, [])
        listed = head + helpers
        missing = set(found) - set(listed)
        if missing:
            raise SystemExit(
                f"{name}: theorems not classified as headline or helper "
                f"in scripts/gen_spec_readme.py: {sorted(missing)}"
            )
        stale = set(listed) - set(found)
        if stale:
            raise SystemExit(f"{name}: listed but not found: {sorted(stale)}")
        parts.append(f"\n## {name}\n")
        for t in head:
            _, line, stmt, summ, full = found[t]
            if summ is None:
                raise SystemExit(f"spec/{name}:{line}: headline theorem {t} has no docstring")
            parts.append(f"\n### `{full}`\n\n{summ} [`spec/{name}:{line}`]({name}#L{line})\n")
            parts.append(f"\n```lean\n{stmt}\n```\n")
        if helpers:
            parts.append("\nHelper lemmas:\n\n")
            for t in helpers:
                line = found[t][1]
                parts.append(f"- `{t}` [`spec/{name}:{line}`]({name}#L{line})\n")
    return "".join(parts)


def main() -> None:
    text = render()
    if sys.argv[1:] == ["--check"]:
        if not OUT.exists() or OUT.read_text() != text:
            raise SystemExit(
                "spec/README.md is stale: run python3 scripts/gen_spec_readme.py"
            )
        print("spec/README.md up to date")
    elif sys.argv[1:]:
        raise SystemExit(__doc__)
    else:
        OUT.write_text(text)
        print(f"wrote {OUT.relative_to(REPO)}")


if __name__ == "__main__":
    main()
